// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_attempt.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

// SECURE: Record a failed login attempt
// name: RecordFailedLoginAttempt :exec
INSERT INTO login_attempts (user_id, ip_address) VALUES ($1, $2);

// SECURE: Check if user is locked due to too many failed attempts
// name: IsUserLocked :one
SELECT EXISTS(
    SELECT 1 FROM login_attempts
    WHERE user_id = $1
    AND attempted_at > NOW() - INTERVAL '30 minutes'
    GROUP BY user_id
    HAVING COUNT(*) >= 5
);

// SECURE: Clear failed login attempts after successful login
// name: ClearFailedLoginAttempts :exec
DELETE FROM login_attempts WHERE user_id = $1;
