// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_history.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

// SECURE: Add a password hash to history
// name: AddPasswordHistory :exec
INSERT INTO password_history (user_id, password_hash) VALUES ($1, $2);

// SECURE: Get recent password history for reuse checking
// name: GetPasswordHistory :many
SELECT id, user_id, password_hash, created_at
FROM password_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2;

// SECURE: Cleanup old password history entries
// name: CleanupOldPasswordHistory :exec
DELETE FROM password_history
WHERE user_id = $1
AND id NOT IN (
    SELECT id FROM password_history
    WHERE user_id = $1
    ORDER BY created_at DESC
    LIMIT $2
);
